defaults :
  - modulus_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

save_filetypes : "vtk,npz"

scheduler:
  decay_rate: 0.95
  decay_steps: 3000

training:
  rec_results_freq : 1000
  rec_constraint_freq: 5000
  max_steps : 110000

batch_size:
  initial_condition: 16384
  interior: 16384
